#!/bin/bash

echo "🎯 Render.com 部署指南 (最簡單方案)"
echo "===================================="
echo ""
echo "✅ 為什麼選擇 Render？"
echo "- 完全免費 (包含PostgreSQL資料庫)"
echo "- GitHub 整合最簡單"
echo "- 不需要複雜的帳戶設定"
echo "- 自動 HTTPS 和網域"
echo ""
echo "🚀 部署步驟 (約3分鐘)："
echo ""
echo "1️⃣ 開啟 Render.com"
echo "   網址: https://render.com"
echo ""
echo "2️⃣ 註冊/登入"
echo "   - 點擊 'Get Started for Free'"
echo "   - 選擇 'GitHub' 登入"
echo "   - 授權 Render 存取您的 GitHub"
echo ""
echo "3️⃣ 建立 Web Service"
echo "   - 點擊 'New +' → 'Web Service'"
echo "   - 選擇 'Build and deploy from a Git repository'"
echo "   - 找到並選擇: chatscai10/-chicken-pos-system"
echo ""
echo "4️⃣ 配置設定"
echo "   - Name: chicken-pos-system"
echo "   - Runtime: Node"
echo "   - Build Command: npm install && npx prisma generate && npm run build"
echo "   - Start Command: node src/test-server.js"
echo ""
echo "5️⃣ 添加 PostgreSQL 資料庫"
echo "   - 在同一個儀表板點擊 'New +' → 'PostgreSQL'"
echo "   - Name: chicken-pos-db"
echo "   - Plan: Free"
echo ""
echo "6️⃣ 設定環境變數"
echo "   - 在 Web Service 設定中添加："
echo "     NODE_ENV = production"
echo "     DATABASE_URL = [PostgreSQL連接字串]"
echo "     JWT_SECRET = [生成隨機字串]"
echo ""
echo "7️⃣ 部署"
echo "   - 點擊 'Create Web Service'"
echo "   - 等待 3-5 分鐘自動建置"
echo ""
echo "📱 您的GitHub倉庫："
echo "https://github.com/chatscai10/-chicken-pos-system"
echo ""
echo "🌐 部署後您會獲得："
echo "- 免費的 .onrender.com 網址"
echo "- 免費的 PostgreSQL 資料庫"
echo "- 自動 HTTPS 憑證"
echo "- 持續部署 (推送代碼自動更新)"
echo ""
echo "🧪 部署完成後執行測試："
echo "./test-deployment.sh https://your-app.onrender.com"
echo ""
echo "🎉 現在就前往 https://render.com 開始部署吧！"

# 嘗試開啟瀏覽器
if command -v explorer.exe &> /dev/null; then
    echo ""
    echo "🌐 正在為您開啟 Render 部署頁面..."
    explorer.exe "https://render.com"
fi